## Local Persistent Volumes ##
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: local-pv-1
spec:
  capacity:
    storage: 0.5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /tmp/disk/vol1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-node1
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: local-pv-2
spec:
  capacity:
    storage: 0.5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /tmp/disk/vol1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-node2
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: local-pv-3
spec:
  capacity:
    storage: 0.5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /tmp/disk/vol1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-node3
## Local Persistent Volumes ##
---
kind: Secret
apiVersion: v1
metadata:
  name: pg-password
  labels: 
    app: pg
type: Opaque
data:
  password: MTEyMjMz
---
# Headless service for stable DNS entries of StatefulSet members.
kind: Service
apiVersion: v1
metadata:
  name: pg
  labels:
    app: pg
spec:
  clusterIP: None
  ports:
    - name: pg
      port: 5432
  selector:
    app: pg
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: pg-write
spec:
  selector:
    matchLabels:
      role: pg-write
  serviceName: pg
  replicas: 1
  template:
    metadata:
      labels:
        app: pg
        role: pg-write
    spec:
      volumes:
        - name: conf
          emptyDir: {}
      initContainers:
        - name: init-pg
          image: postgres:11.1-alpine
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-password
                  key: password
          command:
            - bash
            - "-c"
            - |
              set -e
              # Generate clone data from previous peer.
              [[ `hostname` =~ -([0-9]+)$ ]] || exit 1
              ordinal=${BASH_REMATCH[1]}
              # enable cluster connect
              cat <<EOF >/mnt/conf.d/my_hba.sh
              echo 'host replication postgres 10.244.0.0/16 md5' >> /var/lib/postgresql/data/pg_hba.conf
              EOF
              [[ $ordinal -eq 0 ]] && exit 0
              # Generate clone data from previous peer.
              pg_basebackup -w -R -d "host=pg-write-$(($ordinal-1)).pg user=postgres password=$POSTGRES_PASSWORD" -D /var/lib/postgresql/data
          volumeMounts:
            - name: conf
              mountPath: /mnt/conf.d
            - name: data
              subPath: pgdata
              mountPath: /var/lib/postgresql/data
      containers:
        - name: pg
          image: postgres:11.1-alpine
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-password
                  key: password
          ports:
            - name: pg
              containerPort: 5432
          volumeMounts:
            - name: conf
              mountPath: /docker-entrypoint-initdb.d
            - name: data
              subPath: pgdata
              mountPath: /var/lib/postgresql/data
          livenessProbe:
            exec:
              command:
                - bash
                - "-c"
                - |
                  pg_isready -q
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            exec:
              # Check we can execute queries over TCP (skip-networking is off).
              command:
                - bash
                - "-c"
                - |
                  psql -w -q -U postgres -c "SELECT 1;"
            initialDelaySeconds: 5
            periodSeconds: 2
            timeoutSeconds: 1
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: local-storage
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 0.5Gi
---
# Client service for connecting to any pg instance for reads.
# For writes, you must instead connect to the master: pg-write-0.pg.
kind: Service
apiVersion: v1
metadata:
  name: pg-read
  labels:
    app: pg
spec:
  ports:
    - name: pg
      port: 5432
  selector:
    role: pg-read
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: pg-read
spec:
  selector:
    matchLabels:
      role: pg-read
  serviceName: pg
  replicas: 2
  template:
    metadata:
      labels:
        app: pg
        role: pg-read
    spec:
      volumes:
        - name: conf
          emptyDir: {}
      initContainers:
        - name: init-pg
          image: postgres:11.1-alpine
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-password
                  key: password
          command:
            - bash
            - "-c"
            - |
              set -e
              # Generate clone data from previous peer.
              [[ `hostname` =~ -([0-9]+)$ ]] || exit 1
              ordinal=${BASH_REMATCH[1]}
              # enable cluster connect
              cat <<EOF >/mnt/conf.d/my_hba.sh
              echo 'host replication postgres 10.244.0.0/16 md5' >> /var/lib/postgresql/data/pg_hba.conf
              EOF
              if [[ $ordinal -eq 0 ]]; then
                host = pg-write-0.pg
                # Waiting for postgresql master to be ready (accepting connections)
                until pg_isready -q -h $host; do sleep 1; done
              else
                host = pg-read-$(($ordinal-1)).pg
              fi
              # Generate clone data from previous peer.
              pg_basebackup -w -R -d "host=$host user=postgres password=$POSTGRES_PASSWORD" -D /var/lib/postgresql/data
          volumeMounts:
            - name: conf
              mountPath: /mnt/conf.d
            - name: data
              subPath: pgdata
              mountPath: /var/lib/postgresql/data
      containers:
        - name: pg
          image: postgres:11.1-alpine
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-password
                  key: password
          ports:
            - name: pg
              containerPort: 5432
          volumeMounts:
            - name: conf
              mountPath: /docker-entrypoint-initdb.d
            - name: data
              subPath: pgdata
              mountPath: /var/lib/postgresql/data
          livenessProbe:
            exec:
              command:
                - bash
                - "-c"
                - |
                  pg_isready -q
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            exec:
              # Check we can execute queries over TCP (skip-networking is off).
              command:
                - bash
                - "-c"
                - |
                  psql -w -q -U postgres -c "SELECT 1;"
            initialDelaySeconds: 5
            periodSeconds: 2
            timeoutSeconds: 1
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: local-storage
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 0.5Gi